
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";

import Navbar from "./components/navbar/Navbar";

const inter = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Buckeye Friends School | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children
      }</body>
    </html>
  );
}
